version: '3'

services:
  web:
    build: ./web/
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:9.6.7-alpine
    volumes:
      - ./docker/pg:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - 5433:5432
