version: '3'

services:
  web:
    build: ./web/
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:11.1
    ports:
      - 5433:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d